// Environment configuration
// This file is auto-generated from .env file during build
// DO NOT EDIT THIS FILE MANUALLY - it will be overwritten during build
export const config = {
    FIREBASE_API_KEY: '',
    FIREBASE_AUTH_DOMAIN: '',
    FIREBASE_PROJECT_ID: '',
    FIREBASE_STORAGE_BUCKET: '',
    FIREBASE_MESSAGING_SENDER_ID: '',
    FIREBASE_APP_ID: '',
    FIREBASE_MEASUREMENT_ID: ''
};
